### ISSUE TITLE
Events should have an endpoint to retrieve all my subscriptions

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#1]
## What needs to be solved?
There are currently no way for us to get a list of our subscriptions among the current API endpoints in Events. This makes it very hard to delete subscriptions we no longer need if we have lost the subscription id.

**Comment by acn-sbuad** [comment]
Consideration: should both validated and invalidated subscriptions be included?

**Comment by SandGrainOne** [comment]
> Consideration: should both validated and invalidated subscriptions be included?

Yes, both.

**Comment by tba76** [comment]
Tested, invalidated subscriptions is not included.
