### ISSUE TITLE
Microsoft.IdentityModel.Tokens 6.23.1 causes problem

### ISSUE THREAD

**Issue by vgr** [Altinn/altinn-events#153]
### Description of the bug

Problem discovered in Azure Portal 30.09.2022.

Must re-investigate and reactivate package in Renovate if fixed

### Steps To Reproduce

TODO

### Additional Information

[log in AI](https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%22de41df22-8dd0-435b-98dd-6152cd371e92%22%2C%22ResourceGroup%22%3A%22altinnplatform-at22-rg%22%2C%22Name%22%3A%22at22-platform-ai%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252Fde41df22-8dd0-435b-98dd-6152cd371e92%252FresourceGroups%252Faltinnplatform-at22-rg%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fat22-platform-ai%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%228d948034-4059-11ed-b670-29631ce83417%22%2C%22timestamp%22%3A%222022-09-30T00%3A47%3A53.382Z%22%2C%22cacheId%22%3A%22000a23a3-8483-4fed-a758-adc904014f79%22%2C%22eventTable%22%3A%22exceptions%22%7D)

Exception message
```
System.NotImplementedException:
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.WriteToken (System.IdentityModel.Tokens.Jwt, Version=6.21.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Altinn.Common.AccessTokenClient.Services.AccessTokenGenerator.GenerateAccessToken (Altinn.Common.AccessTokenClient, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null)

```

**Comment by acn-sbuad** [comment]
Running 6.25.0 now
