### ISSUE TITLE
Adding support for generic (external) events

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#159]
### Description

The primary difference between generic(external) events and app events is that Events can't make any assumptions about the content of the events. The `source` will no longer always be a URL pointing to a specific app instance. The `subject` will no longer always be a party. New events might not have an `alternativesubject`, and so on.

This epic assumes that most of the issues related to resilience improvements have been completed.
See: https://github.com/orgs/Altinn/projects/31

This issue will be listing different parts of the work necessary to support more generic events.

#### Access Control
Maskinporten/ID-porten scopes `altinn:events.publish` `altinn:events.subscribe`
- #142 
- #168

#### Authorization
Authorization for events is outside the scope of this epic. It will be implemented as part of a separate epic.
If that implementation is not ready the implementation in this epic will be limited to test-environment, and the access to the scopes will be restricted.
- altinn/altinn-authorization#42

##### OpenAPI Specification
https://app.swaggerhub.com/apis/vgrk/altinn-platform_events/v1
- #125 

##### Blockers (ordered)
1. #112 
2. #118 
3. altinn/altinn-platform#201
4. altinn/altinn-platform#286
5. #120 

##### Implementation
- #103 
- #96 
~~- #165~~ out of scope for epic
- #108 
- #107

#### Internal ("private") API endpoints

- #156
- #109

#### System overview
![generic events drawio](https://user-images.githubusercontent.com/2217340/194832177-9583ae60-4c61-405a-8bb9-4b905f48643b.svg)

**Comment by acn-sbuad** [comment]
All current issues in the epic specified and ready for sprint except #107 and #109

**Comment by annerisbakk** [comment]
Make e new epic

**Comment by acn-sbuad** [comment]
Closing epic as all related dev issues are completed
