### ISSUE TITLE
Create Automated tests for Subscribing and Publishing events

### ISSUE THREAD

**Issue by vgr** [Altinn/altinn-events#166]
The test or set of tests should cover an End-to-End scenario for using Events.
The automated tests should be split across Deploy-tests and Bruksmønster-tests.

The purpose of the subset used in Bruksmønster is to detect service outages related to events components, while the whole set should be run On-Deploy to detect regressions.

(Endpoint validation must be investigated.)

Implementation ideas:
- Each run produce an instance. When events are being sent to the app the events are stored on the instance as DataValues. Test calls /GetInstance to retrieve stored event IDs from DataModel and verify.
- The k6 scripts will create the subscritpion and delete it once done.

Test scenario:
- Create subscription
- Validate endpoint
- Publish event
- Verify that subscriber-endpoint receives event.

## Tasks
- [ ] Tests added to k6 tests for Events, 
    - [ ] Use-case tests
    - [ ] Extended tests
- [ ] QA

**Comment by acn-sbuad** [comment]
K6 tests for subscribing and publishing implemented. Only running in AT and TT for now.
