### ISSUE TITLE
Analysis: functional area definition for Events component

### ISSUE THREAD

**Issue by bdb-dd** [Altinn/altinn-events#170]
### Description

During PR #161, there was a useful discussion about the internal and external capabilities and responsibilities. It will be useful to further define these and use consistent terminology when discussing changes.

### In scope

Better separation between the following two functional areas:
- receiving, storing and querying Cloud Events from external sources, both apps and non-apps (event sink component?)
- forwarding received Cloud Events to external event sinks ("subscribers")

**Comment by acn-sbuad** [comment]
We have agreed on terms publish and  subscribe. For now we have not received any feedback that communication around events has been unclear,so closing for now.
