### ISSUE TITLE
Create altinn:events and delegation schemes in PROD

### ISSUE THREAD

**Issue by vgr** [Altinn/altinn-events#206]
Ref: #168 
The scopes:
- `altinn:events.publish`
- `altinn:events.subscribe` 
has been created for Maskinporten VER2.

And the delegation scheme
- `Altinn API: Publish events`
has been created in TT02

These needs to be created for PROD environments, but it requires a user that have access to these PROD environments for Digdir.

Update scope altinn:events.publish. The scope should not be available to all. Instead access needs to be given.

**Comment by SandGrainOne** [comment]
Completed
