### ISSUE TITLE
Analyze: Create self-service functionality for acquiring access to event subscription

### ISSUE THREAD

**Issue by vgr** [Altinn/altinn-events#207]
### Description

We need to figure out a smart way of handling how a user should acquire access to event subscriptions.
We can let the scope `altinn:events.subscribe` be open for everyone.
- This will allow easy access
- but need to check if this is acceptable wrt. regulations.

### Additional Information

Ref: #168 

Considerations:

Use the same as for instance:read and write?

### Tasks

- [ ]  Identify a convenient way for system integrations to ask for access to the scope(s).
- [ ] Document the procedure.

**Comment by olebhansen** [comment]
the scope `altinn:events.subscribe` is open for everyone.
