### ISSUE TITLE
Analyse: Add logic to prevent duplicate event registration

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#229]
### Description of the bug

After creating the new event-registration queue and logic we've had a few cases where we register the same events to database twice.

One theory is that it can happen if we get an error when trying to put the event on the events-inbound queue. This would cause event-registration to perform a new call to the storage endpoint before attempting to put it on the events-inbound queue again.

Which errors can lead to this? For example the "not yet valid" error with AccessToken?

### Steps To Reproduce

Happens "randomly" and its difficult to reproduce.

### Additional Information

There are currently 342 events where the id has more than one entry in production.

## Tasks
- [x] Investigate if there is a difference in occurances before and after the AccessToken NotBefore change did 21.11.
- [ ] Identify the direct cause of the issue and suggest a possible solution in a new issue

**Comment by b-brodie-digdir** [comment]
First findings:
- 21.11 10:00 - all Events endpoints start failing with SecurityTokenNotYetValid
- 21.11 16:08 - all Events endpoints stop failing.

# events affected: 1500 (all events)

**Comment by b-brodie-digdir** [comment]
Time distribution of duplicate events in prod db:
15.11.22: 15 events distributed between 08:30 and 14:30 ca
14.11.22: 50 events between 12:30 and 21:30 ca
08.11.22: 1 event

Based on this distribution, it is possible that these were isolated events. 

Suggested action:
Setup an alarm that is triggered by changes to a view similar to the following:

```
select * from events.events_app 
where id in (

	select id
	from events.events_app	
	group by id
	having count(*) > 1
	limit 2000
)
order by time desc
```

**Comment by b-brodie-digdir** [comment]
So far not able to reproduce the issue. Suggest creating an alarm in production and tt02 to catch it if the underlying cause is intermittent.

**Comment by SandGrainOne** [comment]
Alarms based on the result of a PostgreSQL query could be interesting, but not something we focus on for this issue. The problem isn't large enough and there are other improvements we can do to reduce the chance for the issue to occur even further.
