### ISSUE TITLE
Align on top level events documentation 

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#243]
Top level of the user documentation should give an introduction of events. 
The team should align on what we want to communicate

WIP for doc : https://github.com/Altinn/altinn-studio-docs/pull/760

## Konklusjon

Altinn Events er et fristilt tjeneste som gir offentlige og private virksomheter mulighet til å få beskjed om hendelser på tvers av virksomheter på en trygg og skalerbar måte. 

Hendelses kilder er som regel offentlige virksomheter, på vegne av seg selv eller andre virksometer og privat personer. 
Hendelses abonnenter er hovedsaklig saksbehandlingssystemer hos offentlige tjenester og private virksomheter. All tilgang til Altinn Events er avtalemessig regulert.

Altinn Events har i lengere tid hatt støtte for "interne" hendelseskilder, Altinn 3 applikasjoner. Tjenesten utvides nå til å støtte generiske kilder uten tilknytning til noe Altinn 3 applikasjon. Fordelen Altinn Events har for digitale tjenester utenfor resten av Altinn sitt tjenesteplatform inkluderer:
* innebygd authorisasjon
* kvalitetssikring av både kilder og abonnenter gjennom standardiserte avtaleverk og innebygd personvern

### Foreslått bruks mønster 

En viktig del av dokumentasjonens innhold er en demonstrasjon av hvordan Altinn Events brukes i dag. Det har blitt foreslått at vi presenterer Skatteetaten sitt bruk av Altinn Events ifm mva innsending. Denne benytter seg av hendelser underveis i arbeidsflyten og er ikke avhengig av noen uferdige endepunkter p.t. Den er også et godt eksempel på bruk av hendelser på tvers av virksomheter, både offentlig og private.

### Terminologi
- Hva er vår definisjon av events? 
- inkluderer både arbeidsflyt hendelser ("app.instance.created") og livshendelser ("company.registered")
  - På engelsk `events`, på norsk `hendelser`
  - Standardisert Event publisher and event subscriber 

### Relevante brukergrupper
- Altinn 3 applikasjoner
- Offentlige Norge
- AS Norge (hendelsesabonnent, indirekte som hendelses subjekt)

Kan du ta i bruk events uten å ta i bruk hele Altinn? Ja.

 
### Why events? 
  - Hva ønsker vi å trekke fram? 
  - Styrken med autorisasjon og at vi henger med i Altinn sin infrasturktur med roller og rettigheter

______________________________

## Fortsatt åpne temaer til fremtidig vurdering

Tiden strak ikke til og flere punkter vil bli nærmere vurdert i nær fremtid.

### Leveransetid / Ytelse / Latens / [insert synonym ]

- Er det et mål for oss å kunne tilby "near" real time? 
  - Er dette et behov kundene våre har? Noe vi ønsker å støtte? 
  - Hva er near real time? 
  - Hvordan måler vi dette? Fra det legges på registration queue til eventet er forsøkt sendt første gang? 
  - Hvilke alternativer har vi: best effort (litt som e-post), delay opptil en dag? Ingen garanti? 

  - Hva vil kunne påvirke leveransetid? 
    - Antall subscribers, antallet andre events i kø, autorisasjon, antallet ulike produsenter i køen, ulike event typer i køen, begrensninger på mottakssiden som rate limiting. 
    - **Hvilke av disse kan vi IKKE leve med at har en negativ påvirkning på leveransetiden og er en faktor vi dermed må skru på under ytelsestestene?** 
 
 - Hvilke tall kan vi garantere for / hvilke mål jobber vi mot.
  - Last: Hvor mange events kan vi prossessere i minuttet?  ( Ved medium last, ved høy last)
  - Hvor lang tid tar det maksimalt fra et event kommer inn til det er prosessert og klart for utsending? 

### Prioritering av events
 - Er dette noe vi ønsker å tilby? 
 - Kan vi unngå at events fra en liten kommune eller sykkelbutikk ikke havner bak en svær utsending fra skatt med et par millioner events? 
 - Egne endepunkt for post avhengig av prioritet med ulik prising? "Altinn Events premium"

## Additional talking points
 - Skalerbarhet. 
  - Queue Storage og Functions: bør vi se på altenrativer her for å få enda bedre ytelse og færre Azure-bindinger? 

### Binding til Azure
  - Hva opplever vi er status quo for events mtp binding til Azure? 
  - Bør det være et uttalt mål for oss at vi ungår bindinger der det er mulig? 

### Gjenbrukbarhet  / OpenSource
  - Bør alle bindinger til Altinn gjøres konfigurerbare ( f.eks. Autorisasjon)?
  - Er dette en kandidat for andre å kunne ta i bruk direkte? 

### Use cases vi har tenkt å støtte
Er dette noe vi trenger å dokumentere? Er det ikke opp til produsent / subscriber hvordan de ønsker å bruke det? 

- høyfrekvente events som pushes helt ut til en nettleser. 
- nettleser vil være en person som er innlogget i nettleser. 

### Bruk av Events-komponenten
  - Hvor ambisiøse ønsker vi å være mtp intern bruk?

**Comment by SandGrainOne** [comment]
In planning 19.12.2022 we decided to close this by creating new smaller issues. Leaving it the sprint with a lower estimate.
