### ISSUE TITLE
Look at the use of `Microsoft.AspNet.WebApi.Client` package from events

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#246]
## Description
The Microsoft.AspNet.WebApi.Client package is getting old. The last version of the package was released in 2018. It's used by at least one component and this is Events, but there might be more. We use it for it's extension methods on HttpContent to deserialize http responses, but there might be more. 

The package has a dependency to `Newtonsoft`.

Up to date extension methods can be found in the System.Net.Http.Json namespace.

## Development tasks
- [x] Remove use of library in ProfileService and RegisterService in Events

## Test
- [x] Regression test

## Acceptance criteria
- [x] No sign of Microsoft.AspNet.WebApi.Client in Events

**Comment by acn-sbuad** [comment]
regression test creation of subscription with alternative subject successful.
