### ISSUE TITLE
Update subscription validation to reduce errors

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-events#250]
## Description

Subscription validation should give up on a subscription if it has been deleted from the database. 

### Steps to reproduce

This procedure requires a working webhook endpoint that responds with OK on the validation call.

0. Temporarily stop the SubscriptionValidation function to prevent validation. This isn't necessary, but makes the next steps easier
1. Create a subscription.
2. (Quickly) delete the subscription.
3. Start the SubscriptionValidation function again.
4. Observe how failing to store the validate flag to the database triggers retry.

## Acceptance criteria

- [x] If subscription is not present it should not cause validation retries.

## Development tasks

- [x] Add handling of missing subscriptions to the logic related to subscription validation.
- [x] QA
- [x] Test

**Comment by acn-sbuad** [comment]
Manual test in AT24 successful. No hidden elements in queue after execution. 
Logged error message: 2023-02-13T10:37:07Z   [Error]   Attempting to validate non existing subscription 310
