### ISSUE TITLE
Support that ORG can push app related events that is not related to a specific instance

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-events#251]
## Description
As an app owner, there could be scenarios to publish events to parties without app changes that are not related to a specific instance. 

As an example. Sirius needs to inform the end-user system about the newly updated prefill. 

```json
[{
  "source":  "https://skd.apps.altinn.no/skd/skattemelding/",
  "subject": "party/1234324",
  "type": "new.prefil.avaiable",
  "time": "2020-02-20T08:00:06.4014168Z",
  "id": "91f2388f-bd8c-4647-8684-fd9f68af5b14",
  "alternativesubject": "/person/01038712345"
}]

```

## Considerations
- We need an API available either in APP for doing this (custom or maybe part of the template) or push API in the platform.

## Acceptance criteria
- Application owner needs to be able to add events for an app for a specific subject. (person/organization)

## Specification tasks

- [ ] Development tasks are defined
- [ ] Test design / decide test need

## Development tasks
> Add tasks here

## Definition of done
Verify that this issue meets [DoD](https://confluence.brreg.no/display/T3KP/Definition+of+Done#DefinitionofDone-DoD%E2%80%93utvikling) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by acn-sbuad** [comment]
Closing issue as we now have support for generic events. This allows app owners to push generic events
