### ISSUE TITLE
Cannot write DateTime with Kind=Unspecified to PostgreSQL type 'timestamp with time zone'

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#28]
### Description of the bug

Found the following error in Application Insights for Platform in TT02:
`Cannot write DateTime with Kind=Unspecified to PostgreSQL type 'timestamp with time zone', only UTC is supported. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior. `

Endpoint: `GET /events/api/v1/app/pat/ps-events-test`

[Full call stack.](https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%22dd6d3e08-a70f-4f71-8847-781ddc5d8468%22%2C%22ResourceGroup%22%3A%22altinnplatform-tt02-rg%22%2C%22Name%22%3A%22tt02-platform-ai%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252Fdd6d3e08-a70f-4f71-8847-781ddc5d8468%252FresourceGroups%252Faltinnplatform-tt02-rg%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Ftt02-platform-ai%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%22c374c363-0272-11ed-97e4-29b42f6e9bf1%22%2C%22timestamp%22%3A%222022-07-13T06%3A12%3A03.829Z%22%2C%22cacheId%22%3A%22725ad201-66f3-4479-b8aa-c56f9f2da1ca%22%2C%22eventTable%22%3A%22requests%22%7D)

### Steps To Reproduce

Request parameter example:
https://altinn-tt02-api.azure-api.net/events/api/v1/app/pat/ps-events-test?from=2022-07-07T11:00:53.3917

## Analysis

Assumed to be caused by the from parameter not having defined time zone. In this case the logic should return 400 Bad Request. Return ProblemDetails object with a description of the error.

## Acceptance Criteria

- [ ] Requests with a timestamp value without timezone should give 400. ProblemDetails with error describing the error.

**Comment by vgr** [comment]
TEST: OK!

Result from testing with the following test:
`GET https://platform.at23.altinn.cloud/events/api/v1/app/ttd/apps-test?size=1&from=<test value>`

| test value | description | result |
| --- | --- | --- |
| 2009-06-15T13:45:30.0000000-07:00 | local offset (o) | 200 OK |
| 2009-06-15T13:45:30.0000000Z | utc (o) | 200 OK |
| 2009-06-15 13:45:30Z | universal sortable (u) | 200 OK |
| Mon, 15 Jun 2009 20:45:30 GMT | RFC1123 pattern (r) | 200 OK |
| Mon%2C%2015%20Jun%202009%2020%3A45%3A30%20GMT | RFC1123 encoded | 200 OK |
| 2009-06-15T13:45:30Z | ~(o)/(s) | 200 OK |
| 2009-06-15T13:45:30.0000000 | unspecified (o)  | 400 Bad Request (1) |
| 2009-06-15T13:45:30 | sortable datetime pattern (s) | 400 Bad Request (1) |
| 1:45 PM | short time pattern (t) | 400 Bad Request (1) |
| June 2009 | | 400 Bad Request (1) |
| Monday, June 15, 2009 1:45:30 PM | | 400 Bad Request (1) |
| 15/06/2009 13:45:30 | | 400 Bad Request (2) |
| 15%2F06%2F2009%2013%3A45%3A30 | encoded | 400 Bad Request (2) |

(1) - The 'From' parameter must specify timezone. E.g. 2022-07-07T11:00:53.3917Z for UTC
(2) - The 'From' or 'After' parameter must be defined.
