### ISSUE TITLE
Hinder Events from duplicating events when storing them to the database

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#307]
### Description

Erorrhandling of inbound events can result in an event being persisted multiple times in the database. 

### Tasks

- [ ] Investigate logs and see if we can find the point of failiure

**Comment by SandGrainOne** [comment]
Refinement 21.03.2023:
The issue isn't serius enough for us to switch our focus to this now. This will instead be taken in when we look at replacing Azure Storage Queue with a Kafka event stream.

**Comment by olebhansen** [comment]
Pending implementation of #573 and subsequent observations to determine if additional work is needed.

**Comment by olebhansen** [comment]
Closing - resolving this in https://github.com/Altinn/altinn-events/issues/588
