### ISSUE TITLE
Ensuring sequential writes to events table

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#322]
### Description

The use of the after parameter in events queries through the API requires that events added to the events table are committed in the order they're being added. 

Look into isolation levels and  transactions 

### Additional Information

This change is intended to be temporary. A better solution would be to provide an events feed not directly reliant on the events table.

### Tasks

- [ ]

**Comment by olebhansen** [comment]
In reality not a issue anymore, and technically this is not possible to fix with the current implementation/pattern (due to how PostgreSQL manages transactions and locks).

Closing issue and making a note for continuation as tech debt/future direction.
