### ISSUE TITLE
Optimize GetEvents function in postgresql

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#323]
### Description

Working with #292 we identified some steps to optimize the retrieval of cloud events. 

### Tasks

- [ ] Modify function
- [ ] QA
- [ ] Manual test

### Acceptance Criterias

- Index is used when retrieving cloud events

**Comment by acn-sbuad** [comment]
Current implementation allows for index to be used for all exact match queries. For components where we support ILIKE, the index is not utilized atm

**Comment by olebhansen** [comment]
No current needs - everything seems sufficiently optimized (for now) :-)
