### ISSUE TITLE
Fix the documentation url

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-events#369]
### Description of the bug

The url https://docs.altinn.studio/api/events/  in the readme seems to be broken. I'm served an error page with text <<Woops. Looks like this page doesn't exist.

[Go to homepage](https://docs.altinn.studio/)>>

### Steps To Reproduce

1. Go to https://github.com/Altinn/altinn-events
2. click on https://docs.altinn.studio/api/events/ in the readme
3. Redirected to error page

Expect the events documentation

**Comment by acn-sbuad** [comment]
fixed
