### ISSUE TITLE
Adjust queries for app events to use resource when possible

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#405]
### Description
Querying app events should also utilize resource, if not possible to consolodate procedures ensure seperate issues is created

### Analysis
Alternatives
1. Create one new PostgreSQL function with support for all scenarios. Identified differences:
    1. AppEvents need to and from dates
    2. Generic events need alternative subject
2. Implement functions as needed for more specific purposes
    1. App events for app owner
    2. App events for party
    3. Generic events as resource owner
    4. Generic events as other

**Comment by SandGrainOne** [comment]
@HenningNormann does an analysis of the queries that use the most CPU and look for possible improvements using resource instead of source as search parameter.

**Comment by HenningNormann** [comment]
https://github.com/Altinn/altinn-events/pull/492

**Comment by SandGrainOne** [comment]
Tested ok
