### ISSUE TITLE
The regression test `GET Todays Events based on party count greater than 0` is unstable

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#499]
### Description of the bug

The regression test `GET Todays Events based on party count greater than 0` is unstable. It will frequently fail right after a new deploy. Run it manually and it will usually work.

### Steps To Reproduce

1. Perform an Events deploy.

**Comment by acn-sbuad** [comment]
Test no longer in use. Current use case tests are stable. Closing  bug.
