### ISSUE TITLE
Update needed for `AccessTokenClient` to latest version in the `Events.Functions`.

### ISSUE THREAD

**Issue by khanrn** [Altinn/altinn-events#503]
### Description

Need to update the `Altinn.Common.AccessTokenClient` to latest version in the `Altinn.Platform.Events.Functions.csproj` file of `Events.Functions`. Renovate may raise a PR if it already hadn't or not got suppressed. 🤔 

### Additional Information

__Related Issue(s) And PR(s)__

- https://github.com/Altinn/altinn-accesstoken/issues/50
- https://github.com/Altinn/altinn-events/pull/496

**Comment by olebhansen** [comment]
Blocked/related to #478
