### ISSUE TITLE
Add GetForOrg tests to use case test

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#506]
### Description

Currently, we have an app owner that relies on the GetForOrg endpoint in Events. 
This endpoint should be included in our use case testing to be able to monitor the stability of the endpoint.

### Tasks

- [ ] Update use case tests to include all or some of the tests defined in altinn-studio\src\test\K6\src\tests\platform\appowner\events.js
- [ ] QA

### Acceptance Criterias

- [ ] We regularly run tests from the perspective of an application owner towards events

**Comment by olebhansen** [comment]
Already covered
