### ISSUE TITLE
Return ProblemDetails for BadRequest

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#54]
### Description

	Currently, bad request responses contain a string with the error message as shown below. 
![image](https://user-images.githubusercontent.com/47737608/182369714-d52e04b1-c6e7-4a55-b41c-1d2e2f8be866.png)

By using the ProblemDetails, as Swagger already claim we do, we can give a response in a more general format. 
E.g.

![image](https://user-images.githubusercontent.com/47737608/182369852-3a074310-628d-4d8f-9704-b8761af68c69.png)

### Acceptance Criterias

All endpoints that produce badRequests use the problem details format instead of a text string

**Comment by SandGrainOne** [comment]
Completed manual testing. Found no surprises.
