### ISSUE TITLE
Avoid duplicate events

### ISSUE THREAD

**Issue by HenningNormann** [Altinn/altinn-events#588]
Ref #333 

Suggested solution
- Introduce a unique index (constraint is not supported for jsonb) in the db for the combo id/source (ref. CloudEvent spec)
- Change the insert sql so that a duplicate is either ignored or the payload is updated (should in theory not be necessary) (sql: "on conflict do update ..." or "on conflict to nothing")

- slette den yngsta

**Comment by SandGrainOne** [comment]
This can't be tested directly and regression testing were successfull.
