### ISSUE TITLE
Replace hardcoded (old and invalid) Slack webhook URL

### ISSUE THREAD

**Issue by hggutvik** [Altinn/altinn-events#608]
### Description

SonarCloud is currently failing our main builds because of [a failed condition (a hardcoded Slack webhook URL in a postman file)](https://sonarcloud.io/project/issues?severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&types=VULNERABILITY&id=Altinn_altinn-events&open=AZFVNkWsrSBd-YeEMY9k) .

Even though the webhook is invalid (verified in local Postman by POSTing it with a simple {"text" : ".."} json payload -> 403 "invalid_token"), we should replace it with a variable reference.

### Acceptance Criterias

The webhook URL is replaced by a variable reference

**Comment by NathalieFroissart** [comment]
size : xs
