### ISSUE TITLE
Separate storing event in db and pushing to queue on POST event

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#68]
### Description

As the code is written now, if storing an event in the db fails and throws an exception, the event is not pushed to the events inbound queue either. These two things could be seperated from each other. 

### Consideration

Can we push an event out before it is stored in the database? Maybe we rather should have retry for the events storage to db? 

### Steps To Reproduce

Study code in EventsService method StoreCloudEvent.

**Comment by SandGrainOne** [comment]
Transfered to other issues.
