### ISSUE TITLE
What restrictions should we have on creation of subscription for app owners?

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#83]
### Description

Currently, an app owner can subscribe to any source as long as the subject isn't specified. In practice this means any application owner kan listen to events from any app by any other application owner.

Is this what we want or should further limitations be introduced?

### Considerations
Events are authorized against policy before being pushed to consumer. An app owner will never receive an event they are not authorized to see. 

### In scope

- Should app owner be limited to only subscription to their own apps? 
- Will an app owner be able to create a token representing the organisation without also getting the app owner attributes? 
- Which events should an organisation be allowed to subscribe to ?

**Comment by SandGrainOne** [comment]
@OddArneSaetervik Could you attempt to answer the questions in this issue?

**Comment by OddArneSaetervik** [comment]
Let's start with the first two questions.
- Should app owner be limited to only create subscriptions to events from their own apps? 
- Which events types should an organisation be allowed to subscribe to?

We cannot rule out that it will be relevant for several organizations (preferably service owners :) to listen to events in a specific app (equivalent to splitting data on form services).
Therefore i imagine that the producer of events (app owner) must enabled to define who should be allowed to subscribe to "their" events: Only themselves, a defined set of organizations or whether it is open for everyone to subscribe.

When an identity first have been granted access to an event source by the app/event owner, the identity should, as a general rule, be able to subscribe to all event types from this source.

**Comment by acn-sbuad** [comment]
Looking through the code again, the authorization before pushing an event to a subscriber will stop an event from being pushed to the app owner if they don't have explicit rights set in the policy file of the app. Hence, the setup today will allow an app owner to set up subscriptions for events from "all" apps, but we will never push an event they are not authorized to receive. 
Thinking this is an issue that can be postponed. Our goal will then be to give reasonable feedback to the consumer when a subscription is generated, in the case there is no policy allowing them to receive any elements

**Comment by SandGrainOne** [comment]
I'm concluding that we've already added restrictions. We just need to implement the check on push of events to new subscriptions as well. See https://github.com/Altinn/altinn-events/issues/239 for further work.
