### ISSUE TITLE
Event hub i et nasjonalt offentlig digitalt økosystem perspektiv; forutsetninger og brukstilfeller.

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#84]
### Forutsetninger
Altinn-events sammen med Altinn-autorisasjon har et betydelig potensiale for å kunne være en sentral event hub for Norge. 
Muligheten for å la Altinn-autorisasjon registere eksterne kilder til events og deretter kunne autorisere produsenter og konsumenter av disse.

### Brukstilfeller
DAN har behov for en mer generisk hendelseskomponent som overordnet gjør det mulig å
* Registrere nye hendelsestyper, med
    * Tekniske regler for hvordan hendelsestypen skal struktureres (JSON schema el.l.) og dermed valideres
    * Evt. beskrivende metadata (identifikator, menneskelesbart navn, beskrivelse, versjon, eier etc) for dokumentasjon 
* Knytte autorisasjonsregler til hendelsestyper som bestemmer hvem som kan 1) produsere og 2) konsumere hendelser av en gitt type
    * Dette kan være faste aktører, som kan produsere/konsumere alle hendelser av en gitt type, eller
    * Dynamiske aktører, gjennom at gitte felter i hendelsen/payload bestemmer hvem som er autorisert for én gitt hendelse

Behovene som vi har i dag: 
* Advokatregisteret
    * DAN skal være distributør av Advokatregisteret pva Tilsynsrådet
    * DAN tilbyr i utgangspunktet et oppslags-API på fødselsnummer
    * Flere potensielle konsumenter vi har snakket med (NAV, UDI, DA) har uttrykt ønske om å kunne så raskt som mulig agere på at en advokat mister bevilgningen
    * I dag løses dette gjennom bulkoverføring av hele registeret, noe Tilsynsrådet vil ha slutt på
    * En hendelsesbasert løsning, der virksomheter som er autoriserte til å gjøre oppslag i registeret også kan abonnere på at advokater faller fra, vil løse dette og eliminere behovet for lokale kopier
* eBevis / andre tjenester som benytter Altinn Samtykke
    * Flere andre datadelingstjenester på DAN benytter Altinn samtykke, hvor det kreves en godkjenning fra parten det gjelder før utlevering av data kan foretas
    * Systemleverandører som Mercell har mange forespørsler om data inne samtidig, hvor de regelmessig poller for å sjekke om svar på samtykkeforespørsler er kommet inn slik at data kan høstes
    * En svært høy andel av trafikken (>99%) inn mot data.altinn.no er polling for å sjekke om samtykkesvar foreligger
    * Med en hendeleseskomponent som lot systemleverandøren oppgi et endepunkt som DAN kan pushe en event til når samtykkesvar mottas, vil kunne drastisk redusere denne trafikken

Andre case i Altinn som ville kunne vært løst med hendelser:
* Digitalt dødsbo
    * Kommunikasjonen mellom bl.a. DA og Altinn vil kunne dra stor nytte av en hendelesbasert tilnærming for å unngå polling. 
* Digital eiendomshandel
    * Svært mye trafikk (prognoser opp mot 1000 req/sek) for denne ene tjenesten for å polle etter nye meldinger
    * Generelt behov i formidlingstjenesten for å varsle om nye meldinger
* Status på correspondence
    * Flere tjenesteeiere i Altinn (f.eks. Forsvaret) poller på API-er for å sjekke om en melding er lest eller ikke.
* Samtykker
    * Generelt behov for å kunne varsle mottaker/håndterer av samtykke om at svar foreligger
* Nye meldinger fra tjenesteeiere
    * BDO og andre løper regelmessig gjennom innboksene til hundretusenvis av kunder hver natt for å kunne agere på nye meldinger fra det offentlige
* Be om tilgangs-forespørsler
* Endringer i tilganger
    * Vi varsler på e-post, men ingen mekanisme for maskinell varsling / overvåkning

**Comment by OddArneSaetervik** [comment]
Erstattes/aktualiseres av road map issue:
https://github.com/Altinn/altinn-roadmap/issues/52
